title: Keynote
content: 'Keynote is an event, which is normally also a lecture, but more like the main event of day or the whole conference'
updated_by: 3c80fd1a-30bb-46e0-b4f9-ecef0c748691
updated_at: 1660134226
blueprint: event_types
