title: 'Panel Discussion'
content: 'Panel Discussions should not have multiple lectures, but multiple speakers, which are answering to question and discuss'
updated_by: 3c80fd1a-30bb-46e0-b4f9-ecef0c748691
updated_at: 1660134069
blueprint: event_types
