title: Roundtable
content: 'Rountable is an event, where every participant is involved into the discussion of moderated topics'
updated_by: 3c80fd1a-30bb-46e0-b4f9-ecef0c748691
updated_at: 1660134114
blueprint: event_types
